export const claimMessage = {
  // Page titles
  title: {
    list: "Quản lý bồi thường",
    detail: "Chi tiết yêu cầu bồi thường",
    byPolicy: "Bồi thường theo đơn bảo hiểm",
    byFarm: "Bồi thường theo nông trại",
  },

  // Table headers
  table: {
    claimNumber: "Mã bồi thường",
    policyNumber: "Số đơn BH",
    farmName: "Nông trại",
    claimAmount: "Số tiền bồi thường",
    status: "Trạng thái",
    triggerTime: "Thời gian kích hoạt",
    autoGenerated: "Tự động",
    partnerDecision: "Quyết định đối tác",
    reviewedBy: "Người xét duyệt",
    createdAt: "Ngày tạo",
    actions: "Thao tác",
  },

  // Claim status
  status: {
    generated: "Đã tạo",
    pending_partner_review: "Chờ đối tác xét duyệt",
    approved: "Đã phê duyệt",
    rejected: "Bị từ chối",
    paid: "Đã thanh toán",
  },

  // Partner decision
  partnerDecision: {
    approved: "Phê duyệt",
    rejected: "Từ chối",
    pending: "Chờ xét duyệt",
  },

  // Filter labels
  filter: {
    title: "Bộ lọc",
    claimNumber: "Mã bồi thường",
    policyId: "Mã đơn bảo hiểm",
    farmId: "Mã nông trại",
    status: "Trạng thái",
    search: "Tìm kiếm...",
    apply: "Áp dụng",
    reset: "Đặt lại",
    allStatus: "Tất cả trạng thái",
  },

  // Detail page sections
  detail: {
    basicInfo: "Thông tin cơ bản",
    claimInfo: "Thông tin bồi thường",
    payoutCalculation: "Tính toán bồi thường",
    reviewInfo: "Thông tin xét duyệt",
    evidenceInfo: "Bằng chứng kích hoạt",
    triggerConditions: "Điều kiện kích hoạt",
    autoApprovalInfo: "Thông tin tự động phê duyệt",
  },

  // Detail fields
  fields: {
    claimId: "Mã bồi thường",
    claimNumber: "Số bồi thường",
    policyId: "Mã đơn bảo hiểm",
    policyNumber: "Số đơn bảo hiểm",
    basePolicyId: "Mã gói bảo hiểm cơ bản",
    farmId: "Mã nông trại",
    farmName: "Tên nông trại",
    triggerId: "Mã điều kiện kích hoạt",
    triggerTimestamp: "Thời gian kích hoạt",
    overThresholdValue: "Giá trị vượt ngưỡng",
    calculatedFixPayout: "Bồi thường cố định",
    calculatedThresholdPayout: "Bồi thường theo ngưỡng",
    claimAmount: "Tổng số tiền bồi thường",
    status: "Trạng thái",
    autoGenerated: "Tự động tạo",
    partnerReviewTime: "Thời gian xét duyệt",
    partnerDecision: "Quyết định của đối tác",
    partnerNotes: "Ghi chú của đối tác",
    reviewedBy: "Người xét duyệt",
    autoApprovalDeadline: "Hạn tự động phê duyệt",
    autoApproved: "Tự động phê duyệt",
    evidenceSummary: "Tóm tắt bằng chứng",
    triggeredAt: "Kích hoạt lúc",
    conditionsCount: "Số điều kiện",
    generationMethod: "Phương thức tạo",
    createdAt: "Ngày tạo",
    updatedAt: "Cập nhật lần cuối",
    yes: "Có",
    no: "Không",
    automatic: "Tự động",
    manual: "Thủ công",
  },

  // Condition fields
  condition: {
    conditionId: "Mã điều kiện",
    parameter: "Tham số",
    measuredValue: "Giá trị đo",
    thresholdValue: "Ngưỡng",
    operator: "Toán tử",
    timestamp: "Thời gian",
    isEarlyWarning: "Cảnh báo sớm",
    consecutiveDays: "Số ngày liên tiếp",
  },

  // Parameters
  parameters: {
    rainfall: "Lượng mưa",
    ndvi: "Chỉ số thực vật (NDVI)",
    ndmi: "Chỉ số độ ẩm (NDMI)",
    temperature: "Nhiệt độ",
  },

  // Statistics
  stats: {
    totalClaims: "Tổng số bồi thường",
    byStatus: "Theo trạng thái",
    totalAmount: "Tổng số tiền",
    avgAmount: "Số tiền trung bình",
    pendingReview: "Chờ xét duyệt",
    approved: "Đã phê duyệt",
    rejected: "Bị từ chối",
    paid: "Đã thanh toán",
  },

  // Actions
  actions: {
    viewDetail: "Xem chi tiết",
    viewPolicy: "Xem đơn BH",
    viewFarm: "Xem nông trại",
    back: "Quay lại",
    export: "Xuất Excel",
    testTrigger: "Giả lập điều kiện",
    submitTest: "Thực hiện kiểm tra",
    addCondition: "Thêm điều kiện",
    removeCondition: "Xóa điều kiện",
  },

  // Success messages
  success: {
    fetchList: "Tải danh sách bồi thường thành công",
    fetchDetail: "Tải chi tiết bồi thường thành công",
  },

  // Error messages
  error: {
    fetchList: "Không thể tải danh sách bồi thường",
    fetchDetail: "Không thể tải chi tiết bồi thường",
    invalidClaimId: "Mã bồi thường không hợp lệ",
    notFound: "Không tìm thấy yêu cầu bồi thường",
    unauthorized: "Bạn không có quyền thực hiện thao tác này",
    serverError: "Lỗi máy chủ, vui lòng thử lại sau",
  },

  // Loading messages
  loading: {
    list: "Đang tải danh sách...",
    detail: "Đang tải chi tiết...",
  },

  // Empty states
  empty: {
    list: "Không có yêu cầu bồi thường nào",
    filter: "Không tìm thấy bồi thường phù hợp với bộ lọc",
    evidence: "Chưa có bằng chứng",
    conditions: "Chưa có điều kiện kích hoạt",
  },

  // Test Trigger Feature
  testTrigger: {
    // Success messages
    testSuccess:
      "Dữ liệu test được gửi thành công. Yêu cầu bồi thường đã được tạo nếu điều kiện thỏa mãn.",

    // Data quality options (matching BE enum)
    dataQuality: {
      good: "Tốt",
      acceptable: "Chấp Nhận Được",
      poor: "Kém",
    },

    // Validation errors
    validation: {
      policyRequired: "Vui lòng chọn đơn bảo hiểm",
      farmIdRequired: "Không tìm thấy thông tin trang trại từ đơn bảo hiểm",
      dataSourceRequired: "Vui lòng chọn nguồn dữ liệu (Data Source)",
      parameterRequired: "Vui lòng nhập tên tham số",
      measuredValueRequired: "Vui lòng nhập giá trị đo",
      measuredValueInvalid: "Giá trị đo phải là số hợp lệ",
      confidenceScoreRange: "Điểm tin cậy phải nằm trong khoảng 0.0 - 1.0",
      timestampInvalid: "Thời gian đo không hợp lệ",
      componentDataInvalidJson: "Dữ liệu thành phần phải là JSON hợp lệ",
      noConditions: "Vui lòng thêm ít nhất một điều kiện",
    },

    // Backend error mapping (Vietnamese translations)
    errors: {
      UNAUTHORIZED:
        "Bạn không có quyền thực hiện thao tác này. Vui lòng đăng nhập lại.",
      INVALID_UUID:
        "Mã đơn bảo hiểm không hợp lệ. Vui lòng chọn lại đơn bảo hiểm.",
      INVALID_REQUEST:
        "Dữ liệu gửi lên không hợp lệ. Vui lòng kiểm tra lại thông tin.",
      VALIDATION_ERROR:
        "Dữ liệu giám sát không được để trống. Vui lòng thêm ít nhất một điều kiện.",
      TEST_FAILED:
        "Không thể thực hiện test. Đơn bảo hiểm không tồn tại hoặc đã bị hủy.",
      POLICY_NOT_FOUND: "Không tìm thấy đơn bảo hiểm. Vui lòng kiểm tra lại.",
      POLICY_BLOCKED:
        "Đơn bảo hiểm đã bị khóa hoặc hết hiệu lực. Không thể thực hiện test.",
      NETWORK_ERROR:
        "Lỗi kết nối mạng. Vui lòng kiểm tra kết nối internet và thử lại.",
      TIMEOUT: "Yêu cầu quá thời gian chờ. Vui lòng thử lại.",
      SERVER_ERROR:
        "Lỗi máy chủ. Vui lòng thử lại sau hoặc liên hệ quản trị viên.",
      UNKNOWN: "Đã xảy ra lỗi không xác định. Vui lòng thử lại sau.",
    },
  },
};
