export const claimMessage = {
  // Page titles
  title: {
    list: "Quản lý bồi thường",
    detail: "Chi tiết yêu cầu bồi thường",
    byPolicy: "Bồi thường theo đơn bảo hiểm",
    byFarm: "Bồi thường theo nông trại",
  },

  // Table headers
  table: {
    claimNumber: "Mã bồi thường",
    policyNumber: "Số đơn BH",
    farmName: "Nông trại",
    claimAmount: "Số tiền bồi thường",
    status: "Trạng thái",
    triggerTime: "Thời gian kích hoạt",
    autoGenerated: "Tự động",
    partnerDecision: "Quyết định đối tác",
    reviewedBy: "Người xét duyệt",
    createdAt: "Ngày tạo",
    actions: "Thao tác",
  },

  // Claim status
  status: {
    generated: "Đã tạo",
    pending_partner_review: "Chờ đối tác xét duyệt",
    approved: "Đã phê duyệt",
    rejected: "Bị từ chối",
    paid: "Đã thanh toán",
  },

  // Partner decision
  partnerDecision: {
    approved: "Phê duyệt",
    rejected: "Từ chối",
    pending: "Chờ xét duyệt",
  },

  // Filter labels
  filter: {
    title: "Bộ lọc",
    claimNumber: "Mã bồi thường",
    policyId: "Mã đơn bảo hiểm",
    farmId: "Mã nông trại",
    status: "Trạng thái",
    search: "Tìm kiếm...",
    apply: "Áp dụng",
    reset: "Đặt lại",
    allStatus: "Tất cả trạng thái",
  },

  // Detail page sections
  detail: {
    basicInfo: "Thông tin cơ bản",
    claimInfo: "Thông tin bồi thường",
    payoutCalculation: "Tính toán bồi thường",
    reviewInfo: "Thông tin xét duyệt",
    evidenceInfo: "Bằng chứng kích hoạt",
    triggerConditions: "Điều kiện kích hoạt",
    autoApprovalInfo: "Thông tin tự động phê duyệt",
  },

  // Detail fields
  fields: {
    claimId: "Mã bồi thường",
    claimNumber: "Số bồi thường",
    policyId: "Mã đơn bảo hiểm",
    policyNumber: "Số đơn bảo hiểm",
    basePolicyId: "Mã gói bảo hiểm cơ bản",
    farmId: "Mã nông trại",
    farmName: "Tên nông trại",
    triggerId: "Mã điều kiện kích hoạt",
    triggerTimestamp: "Thời gian kích hoạt",
    overThresholdValue: "Giá trị vượt ngưỡng",
    calculatedFixPayout: "Bồi thường cố định",
    calculatedThresholdPayout: "Bồi thường theo ngưỡng",
    claimAmount: "Tổng số tiền bồi thường",
    status: "Trạng thái",
    autoGenerated: "Tự động tạo",
    partnerReviewTime: "Thời gian xét duyệt",
    partnerDecision: "Quyết định của đối tác",
    partnerNotes: "Ghi chú của đối tác",
    reviewedBy: "Người xét duyệt",
    autoApprovalDeadline: "Hạn tự động phê duyệt",
    autoApproved: "Tự động phê duyệt",
    evidenceSummary: "Tóm tắt bằng chứng",
    triggeredAt: "Kích hoạt lúc",
    conditionsCount: "Số điều kiện",
    generationMethod: "Phương thức tạo",
    createdAt: "Ngày tạo",
    updatedAt: "Cập nhật lần cuối",
    yes: "Có",
    no: "Không",
    automatic: "Tự động",
    manual: "Thủ công",
  },

  // Condition fields
  condition: {
    conditionId: "Mã điều kiện",
    parameter: "Tham số",
    measuredValue: "Giá trị đo",
    thresholdValue: "Ngưỡng",
    operator: "Toán tử",
    timestamp: "Thời gian",
    isEarlyWarning: "Cảnh báo sớm",
    consecutiveDays: "Số ngày liên tiếp",
  },

  // Parameters
  parameters: {
    rainfall: "Lượng mưa",
    ndvi: "Chỉ số thực vật (NDVI)",
    ndmi: "Chỉ số độ ẩm (NDMI)",
    temperature: "Nhiệt độ",
  },

  // Statistics
  stats: {
    totalClaims: "Tổng số bồi thường",
    byStatus: "Theo trạng thái",
    totalAmount: "Tổng số tiền",
    avgAmount: "Số tiền trung bình",
    pendingReview: "Chờ xét duyệt",
    approved: "Đã phê duyệt",
    rejected: "Bị từ chối",
    paid: "Đã thanh toán",
  },

  // Actions
  actions: {
    viewDetail: "Xem chi tiết",
    viewPolicy: "Xem đơn BH",
    viewFarm: "Xem nông trại",
    back: "Quay lại",
    export: "Xuất Excel",
    testTrigger: "Giả lập điều kiện",
    submitTest: "Thực hiện kiểm tra",
    addCondition: "Thêm điều kiện",
    removeCondition: "Xóa điều kiện",
  },

  // Success messages
  success: {
    fetchList: "Tải danh sách bồi thường thành công",
    fetchDetail: "Tải chi tiết bồi thường thành công",
  },

  // Error messages
  error: {
    fetchList: "Không thể tải danh sách bồi thường",
    fetchDetail: "Không thể tải chi tiết bồi thường",
    invalidClaimId: "Mã bồi thường không hợp lệ",
    notFound: "Không tìm thấy yêu cầu bồi thường",
    unauthorized: "Bạn không có quyền thực hiện thao tác này",
    serverError: "Lỗi máy chủ, vui lòng thử lại sau",
  },

  // Loading messages
  loading: {
    list: "Đang tải danh sách...",
    detail: "Đang tải chi tiết...",
  },

  // Empty states
  empty: {
    list: "Không có yêu cầu bồi thường nào",
    filter: "Không tìm thấy bồi thường phù hợp với bộ lọc",
    evidence: "Chưa có bằng chứng",
    conditions: "Chưa có điều kiện kích hoạt",
  },

  // Test Trigger Feature
  testTrigger: {
    title: "Giả lập điều kiện kích hoạt bồi thường",
    subtitle:
      "Tạo dữ liệu giả lập để kiểm tra điều kiện kích hoạt và tạo yêu cầu bồi thường",
    selectPolicy: "Chọn đơn bảo hiểm",
    policyPlaceholder: "Chọn hoặc tìm kiếm đơn bảo hiểm...",
    monitoringDataSection: "Dữ liệu giám sát giả lập",
    conditionIdLabel: "Mã điều kiện kích hoạt",
    conditionIdPlaceholder: "Nhập mã UUID của điều kiện",
    conditionIdTooltip:
      "Base Policy Trigger Condition ID - Phải khớp với điều kiện trong policy",
    parameterLabel: "Tên tham số",
    parameterPlaceholder: "Chọn tham số đo lường",
    measuredValueLabel: "Giá trị đo",
    measuredValuePlaceholder: "Nhập giá trị đo (phải vượt ngưỡng để tạo claim)",
    measuredValueTooltip:
      "Giá trị này sẽ được so sánh với ngưỡng trong điều kiện",
    unitLabel: "Đơn vị",
    unitPlaceholder: "Ví dụ: mm, °C, index",
    timestampLabel: "Thời gian đo (Unix timestamp)",
    timestampPlaceholder: "Để trống sẽ dùng thời gian hiện tại",
    dataQualityLabel: "Chất lượng dữ liệu",
    confidenceScoreLabel: "Điểm tin cậy",
    confidenceScorePlaceholder: "Giá trị từ 0.0 đến 1.0",
    measurementSourceLabel: "Nguồn đo",
    measurementSourcePlaceholder: "Ví dụ: satellite, sensor, manual",
    checkPolicyLabel: "Kiểm tra điều kiện policy",
    checkPolicyTooltip:
      "Nếu bật, hệ thống sẽ đánh giá điều kiện kích hoạt và tạo claim nếu thỏa mãn",
    resultSection: "Kết quả kiểm tra",
    testSuccessTitle: "Kiểm tra thành công!",
    testSuccess: "Dữ liệu giả lập đã được gửi và xử lý thành công",
    claimsGenerated: "Bồi thường được tạo",
    dataStored: "Dữ liệu đã được lưu",
    testDataCount: "Số điều kiện đã test",
    checkPolicyEnabled: "Đã kiểm tra điều kiện",
    viewClaims: "Xem danh sách bồi thường",
    testAgain: "Test lại",
    parameters: {
      rainfall: "Lượng mưa (rainfall)",
      ndvi: "Chỉ số thực vật - NDVI (ndvi)",
      ndmi: "Chỉ số độ ẩm - NDMI (ndmi)",
      temperature: "Nhiệt độ (temperature)",
      soil_moisture: "Độ ẩm đất (soil_moisture)",
    },
    dataQuality: {
      excellent: "Xuất sắc (excellent)",
      good: "Tốt (good)",
      fair: "Khá (fair)",
      poor: "Kém (poor)",
    },
    helpText: {
      title: "Hướng dẫn sử dụng",
      step1: "1. Tìm kiếm và chọn đơn bảo hiểm cần test từ danh sách",
      step2:
        "2. Chọn điều kiện kích hoạt từ policy (tự động load sau khi chọn đơn)",
      step3:
        "3. Chọn Data Source để tự động điền tên tham số, đơn vị và nguồn đo",
      step4:
        "4. Nhập giá trị đo (phải vượt ngưỡng trong điều kiện để tạo claim)",
      step5:
        "5. Chọn ngày giờ đo dữ liệu (sẽ tự động chuyển sang Unix timestamp)",
      note: "Lưu ý: Chọn Data Source để tự động điền thông tin, hoặc có thể nhập thủ công. Chỉ tạo claim nếu giá trị đo vượt ngưỡng.",
    },
  },
};
