import AntdConfigProvider from "@/providers/andtd-config-provider";
import AuthRefreshProvider from "@/providers/auth-refresh-provider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Admin Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdConfigProvider>
          <AuthRefreshProvider>{children}</AuthRefreshProvider>
        </AntdConfigProvider>
      </body>
    </html>
  );
}
